#!/usr/bin/env python3
"""Build data/base.js from Natural Earth 10m GeoJSON (public domain).

Usage:
    python3 tools/build_base.py <dir-with-natural-earth-geojson>

Needed files (from github.com/nvkelso/natural-earth-vector/tree/master/geojson):
    ne_10m_admin_1_states_provinces.geojson
    ne_10m_rivers_lake_centerlines.geojson
    ne_10m_rivers_europe.geojson
    ne_10m_lakes.geojson, ne_10m_lakes_europe.geojson
    ne_10m_populated_places_simple.geojson

Output is a plain JS file (window.GR_BASE = {...}) so the app works when
index.html is opened straight from disk (file:// cannot fetch JSON).
Requires: shapely.
"""
import json
import os
import sys

from shapely.geometry import mapping, shape
from shapely.ops import unary_union

SRC = sys.argv[1] if len(sys.argv) > 1 else "."
OUT = os.path.join(os.path.dirname(__file__), "..", "data", "base.js")


def load(name):
    with open(os.path.join(SRC, name + ".geojson")) as f:
        return json.load(f)["features"]


def rnd(geom, nd=4):
    """Round coordinates to shrink output."""
    def r(c):
        if isinstance(c[0], (int, float)):
            return [round(c[0], nd), round(c[1], nd)]
        return [r(x) for x in c]
    g = mapping(geom)
    return {"type": g["type"], "coordinates": r(g["coordinates"])}


# Oblasts: internationally recognised borders (Crimea + Sevastopol included).
oblasts = []
for f in load("ne_10m_admin_1_states_provinces"):
    p = f["properties"]
    if not str(p.get("iso_3166_2", "")).startswith("UA-"):
        continue
    g = shape(f["geometry"]).simplify(0.004, preserve_topology=True)
    oblasts.append({
        "type": "Feature",
        "properties": {"name": p["name"], "name_uk": p.get("name_uk"), "iso": p["iso_3166_2"]},
        "geometry": rnd(g),
        "_g": g,
    })
border = unary_union([o["_g"] for o in oblasts]).buffer(0)
border_s = border.simplify(0.003, preserve_topology=True)
for o in oblasts:
    del o["_g"]

clip = border.buffer(0.35)

rivers = []
for src in ("ne_10m_rivers_lake_centerlines", "ne_10m_rivers_europe"):
    for f in load(src):
        g = shape(f["geometry"])
        if not g.intersects(clip):
            continue
        g = g.intersection(clip).simplify(0.002)
        if g.is_empty or g.length < 0.05:
            continue
        p = f["properties"]
        rivers.append({
            "type": "Feature",
            "properties": {
                "name": p.get("name_en") or p.get("name") or "",
                "rank": p.get("scalerank"),
                "src": "Natural Earth",
            },
            "geometry": rnd(g),
        })

lakes = []
for src in ("ne_10m_lakes", "ne_10m_lakes_europe"):
    for f in load(src):
        g = shape(f["geometry"])
        if g.intersects(clip):
            g = g.intersection(clip).simplify(0.003)
            if not g.is_empty:
                lakes.append({"type": "Feature", "properties": {"name": f["properties"].get("name")},
                              "geometry": rnd(g)})

places = []
for f in load("ne_10m_populated_places_simple"):
    p = f["properties"]
    if p.get("adm0_a3") != "UKR" and p.get("sov_a3") != "UKR":
        continue
    x, y = f["geometry"]["coordinates"]
    places.append({"n": p["name"], "lat": round(y, 3), "lon": round(x, 3),
                   "r": p.get("scalerank"), "pop": p.get("pop_max")})

data = {
    "source": "Natural Earth 10m (public domain), simplified",
    "border": {"type": "Feature", "properties": {}, "geometry": rnd(border_s)},
    "oblasts": {"type": "FeatureCollection", "features": oblasts},
    "rivers": {"type": "FeatureCollection", "features": rivers},
    "lakes": {"type": "FeatureCollection", "features": lakes},
    "places": places,
}
with open(OUT, "w") as f:
    f.write("/* Generated by tools/build_base.py from Natural Earth. Do not edit. */\n")
    f.write("window.GR_BASE = ")
    json.dump(data, f, separators=(",", ":"), ensure_ascii=False)
    f.write(";\n")
print("wrote", OUT, os.path.getsize(OUT), "bytes;", len(rivers), "rivers,", len(places), "places")
